/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.databaseproject;

import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class AddAssetDialog extends javax.swing.JDialog {

    public AddAssetDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);

        loadCategories();
        loadLocations();
    }

    // load combos
    private void loadCategories() {
        try (ResultSet rs = DatabaseHelper.executeQuery(
                "SELECT CategoryID, CategoryName FROM AssetCategory ORDER BY CategoryName")) {

            while (rs.next()) {
                cmbCategory.addItem(new ComboItem(
                        rs.getInt("CategoryID"),
                        rs.getString("CategoryName")
                ));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading categories");
        }
    }

    private void loadLocations() {
        cmbLocation.addItem(null); // optional
        try (ResultSet rs = DatabaseHelper.executeQuery(
                "SELECT LocationID, LocationName FROM Location ORDER BY LocationName")) {

            while (rs.next()) {
                cmbLocation.addItem(new ComboItem(
                        rs.getInt("LocationID"),
                        rs.getString("LocationName")
                ));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading locations");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtAssetName = new javax.swing.JTextField();
        cmbCategory = new javax.swing.JComboBox<>();
        cmbLocation = new javax.swing.JComboBox<>();
        txtSerialNumber = new javax.swing.JTextField();
        txtPurchasePrice = new javax.swing.JTextField();
        txtPurchaseDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        spnQuantity = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Asset");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 22, 121, -1));

        jLabel2.setText("Asset Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 77, 100, -1));

        jLabel3.setText("Category:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 117, 100, -1));

        jLabel4.setText("Location:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 157, 100, -1));

        jLabel5.setText("Serial Number:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 237, 100, -1));

        jLabel6.setText("Purchase Date:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 277, 100, -1));

        jLabel7.setText("Purchase Price:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 317, 100, -1));

        jLabel8.setText("Notes:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 370, 80, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 510, -1, -1));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 510, -1, -1));
        getContentPane().add(txtAssetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 74, 146, -1));

        getContentPane().add(cmbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 114, 146, -1));

        getContentPane().add(cmbLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 154, 146, -1));
        getContentPane().add(txtSerialNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 234, 146, -1));
        getContentPane().add(txtPurchasePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 314, 146, -1));
        getContentPane().add(txtPurchaseDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 274, 146, -1));

        txtNotes.setColumns(20);
        txtNotes.setRows(5);
        jScrollPane1.setViewportView(txtNotes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 339, 258, 96));

        jLabel9.setText("Quantity:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 197, 100, -1));

        spnQuantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1000, 1));
        getContentPane().add(spnQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 194, 76, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int quantity = (int) spnQuantity.getValue();

        try {
            // Validate required fields
            if (txtAssetName.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Asset name is required.");
                return;
            }
            if (cmbCategory.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Please select a category.");
                return;
            }
            if (txtPurchasePrice.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Purchase price is required.");
                return;
            }
            double price;
            try {
                price = Double.parseDouble(txtPurchasePrice.getText());
                if (price <= 10) {
                    throw new NumberFormatException();
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Invalid purchase price.");
                return;
            }
            LocalDate purchaseDate;
            try {
                purchaseDate = LocalDate.parse(txtPurchaseDate.getText().trim());
                if (purchaseDate.isAfter(LocalDate.now())) {
                    JOptionPane.showMessageDialog(this,
                            "Purchase date cannot be in the future.");
                    return;
                }
            } catch (DateTimeParseException ex) {
                JOptionPane.showMessageDialog(this,
                        "Invalid purchase date format. Use YYYY-MM-DD.");
                return;
            }

            ComboItem category = (ComboItem) cmbCategory.getSelectedItem();
            ComboItem location = (ComboItem) cmbLocation.getSelectedItem();
            int inStockStatusId = getStatusIdByName("In Stock");
            String sql
                    = "INSERT INTO FixedAsset "
                    + "(AssetName, CategoryID, StatusID, LocationID, SerialNumber, "
                    + "PurchaseDate, PurchasePrice, Quantity, Notes) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

            DatabaseHelper.executeUpdate(
                    sql,
                    txtAssetName.getText(),
                    category.getId(),
                    inStockStatusId,
                    location == null ? null : location.getId(),
                    txtSerialNumber.getText(),
                    purchaseDate, // validated LocalDate
                    price,
                    quantity,
                    txtNotes.getText()
            );
            JOptionPane.showMessageDialog(this, "Asset added successfully.");
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error adding asset: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private int getStatusIdByName(String statusName) throws Exception {
        String sql = "SELECT StatusID FROM AssetStatus WHERE StatusName = ?";
        try (ResultSet rs = DatabaseHelper.executeQuery(sql, statusName)) {
            if (rs.next()) {
                return rs.getInt("StatusID");
            }
        }
        throw new Exception("Status not found: " + statusName);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<ComboItem> cmbCategory;
    private javax.swing.JComboBox<ComboItem> cmbLocation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spnQuantity;
    private javax.swing.JTextField txtAssetName;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextField txtPurchaseDate;
    private javax.swing.JTextField txtPurchasePrice;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables
}
