/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.databaseproject;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author hadalkharouf
 */
public class AddCarDialog extends javax.swing.JDialog {

    private boolean succeeded = false; // to tell parent if insert worked

    /**
     * Creates new form AddCarDialog
     */
    public AddCarDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        loadModels();
        loadStatuses();
        loadSuppliers();
        loadLocations();
    }

    private void loadModels() {
        String sql = "SELECT ModelID, ModelName FROM CarModel";
        try (ResultSet rs = DatabaseHelper.executeQuery(sql)) {
            cmbModel.removeAllItems();
            while (rs.next()) {
                int id = rs.getInt("ModelID");
                String name = rs.getString("ModelName");
                cmbModel.addItem(new ComboItem(id, name));
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading models.");
        }
    }

    private void loadStatuses() {
        String sql = "SELECT StatusID, StatusName FROM CarStatus";
        try (ResultSet rs = DatabaseHelper.executeQuery(sql)) {
            cmbStatus.removeAllItems();
            while (rs.next()) {
                int id = rs.getInt("StatusID");
                String name = rs.getString("StatusName");
                cmbStatus.addItem(new ComboItem(id, name));
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading statuses.");
        }
    }

    private void loadSuppliers() {
        String sql = "SELECT SupplierID, SupplierName FROM Supplier";
        try (ResultSet rs = DatabaseHelper.executeQuery(sql)) {
            cmbSupplier.removeAllItems();
            while (rs.next()) {
                int id = rs.getInt("SupplierID");
                String name = rs.getString("SupplierName");
                cmbSupplier.addItem(new ComboItem(id, name));
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading suppliers.");
        }
    }

    private void loadLocations() {
        String sql = "SELECT LocationID, LocationName FROM Location";
        try (ResultSet rs = DatabaseHelper.executeQuery(sql)) {
            cmbLocation.removeAllItems();
            while (rs.next()) {
                int id = rs.getInt("LocationID");
                String name = rs.getString("LocationName");
                cmbLocation.addItem(new ComboItem(id, name));
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading locations.");
        }
    }

    private boolean plateExists(String plate) {
        String sql = "SELECT COUNT(*) FROM Car WHERE PlateNumber = ?";
        try (ResultSet rs = DatabaseHelper.executeQuery(sql, plate)) {
            if (rs.next()) {
                return rs.getInt(1) > 0; // true if exists
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }

    public boolean isSucceeded() {
        return succeeded;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMileage = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtVIN = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtPlate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbLocation = new javax.swing.JComboBox<>();
        cmbSupplier = new javax.swing.JComboBox<>();
        cmbStatus = new javax.swing.JComboBox<>();
        cmbModel = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("VIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel2.setText("Plate Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel3.setText("Year");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel4.setText("Color");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));
        getContentPane().add(txtMileage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 130, -1));

        jLabel5.setText("Mileage");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        getContentPane().add(txtVIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 130, -1));
        getContentPane().add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 130, -1));
        getContentPane().add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 130, -1));
        getContentPane().add(txtPlate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 130, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel6.setText("Car Details ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel7.setText("Car Attributes");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jLabel8.setText("Location");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        jLabel9.setText("Supplier");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        jLabel10.setText("Status");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jLabel11.setText("Model");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        getContentPane().add(cmbLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 110, 20));

        getContentPane().add(cmbSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 110, 20));

        getContentPane().add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 110, 20));

        getContentPane().add(cmbModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 93, 110, 20));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 270, 230));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 260, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

            // ----- VALIDATION -----
            
        String vin = txtVIN.getText().trim();
        String plate = txtPlate.getText().trim();
        String yearText = txtYear.getText().trim();
        String color = txtColor.getText().trim();
        String mileageText = txtMileage.getText().trim();

        // 1) Required fields
        if (vin.isEmpty() || plate.isEmpty() || yearText.isEmpty()
                || color.isEmpty() || mileageText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields.");
            return;
        }

        // 2) Duplicate plate
        if (plateExists(plate)) {
            JOptionPane.showMessageDialog(this, "Plate number already exists!");
            return;
        }

        // 3) Numbers validation
        int year;
        int mileage;

        try {
            year = Integer.parseInt(yearText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Year must be a number.");
            return;
        }

        try {
            mileage = Integer.parseInt(mileageText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Mileage must be a number.");
            return;
        }

        // Year range check
        if (year < 1950 || year > 2050) {
            JOptionPane.showMessageDialog(this, "Enter a valid year (1950–2050).");
            return;
        }

        // ----- END VALIDATION -----
        
        // check empty
        if (plate.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Plate number is required.");
            return;
        }

        // 2) Check duplicate
        if (plateExists(plate)) {
            JOptionPane.showMessageDialog(this, "Plate number already exists!");
            return;
        }
        
        try {

            if (vin.isEmpty() || plate.isEmpty()
                    || cmbModel.getSelectedItem() == null
                    || cmbStatus.getSelectedItem() == null
                    || cmbSupplier.getSelectedItem() == null
                    || cmbLocation.getSelectedItem() == null) {

                JOptionPane.showMessageDialog(this, "Please fill required fields.");
                return;
            }

            if (!yearText.isEmpty()) {
                year = Integer.parseInt(yearText);
            }

            if (!mileageText.isEmpty()) {
                mileage = Integer.parseInt(mileageText);
            }

            ComboItem modelItem = (ComboItem) cmbModel.getSelectedItem();
            ComboItem statusItem = (ComboItem) cmbStatus.getSelectedItem();
            ComboItem supplierItem = (ComboItem) cmbSupplier.getSelectedItem();
            ComboItem locationItem = (ComboItem) cmbLocation.getSelectedItem();

            int modelId = modelItem.getId();
            int statusId = statusItem.getId();
            int supplierId = supplierItem.getId();
            int locationId = locationItem.getId();

            // Only insert required + some optional fields
            String sql = "INSERT INTO Car "
                    + "(ModelID, VIN, PlateNumber, Year, Color, Mileage, "
                    + "StatusID, SupplierID, LocationID) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

            int rows = DatabaseHelper.executeUpdate(sql,
                    modelId,
                    vin,
                    plate,
                    year,
                    color,
                    mileage,
                    statusId,
                    supplierId,
                    locationId
            );

            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Car added successfully.");
                succeeded = true;
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "No row inserted.");
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Year and Mileage must be numbers.");
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error saving car.");
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        succeeded = false;
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCarDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCarDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCarDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCarDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddCarDialog dialog = new AddCarDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<ComboItem> cmbLocation;
    private javax.swing.JComboBox<ComboItem> cmbModel;
    private javax.swing.JComboBox<ComboItem> cmbStatus;
    private javax.swing.JComboBox<ComboItem> cmbSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtMileage;
    private javax.swing.JTextField txtPlate;
    private javax.swing.JTextField txtVIN;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
