/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.databaseproject;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class AddUserDialog extends javax.swing.JDialog {

    
    public AddUserDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        loadRoles();
        comboRole.addActionListener(e -> roleChanged());
        loadEmployees();
    }
    
    private void loadRoles() {
        try {
            ResultSet rs = DatabaseHelper.executeQuery(
                "SELECT RoleID, RoleName FROM UserRole"
            );
            comboRole.removeAllItems();
            
            while (rs.next()) {
                comboRole.addItem(
                    new ComboItem(
                        rs.getInt("RoleID"),
                        rs.getString("RoleName")
                    )
                );
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading roles: " + e.getMessage());
        }
    }
    
    private void loadEmployees() {
        try {
            ResultSet rs = DatabaseHelper.executeQuery(
                "SELECT EmployeeID, FirstName, LastName FROM Employee"
            );
            comboEmployee.removeAllItems();
            comboEmployee.addItem(null); // Allow NULL employee

            while (rs.next()) {
                comboEmployee.addItem(
                    new ComboItem(
                        rs.getInt("EmployeeID"),
                        rs.getString("FirstName") + " " + rs.getString("LastName")
                    )
                );
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading employees: " + e.getMessage());
        }
    }
    
    // --------- Validation ----------
    private boolean usernameExists(String username) {
        try {
            ResultSet rs = DatabaseHelper.executeQuery(
                "SELECT COUNT(*) FROM UserAccount WHERE UserName = ?",
                username
            );
            if (rs.next()) {
                return rs.getInt(1) > 0;
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error checking username.");
        }
        return false;
    }
    
    // ------- Role Logic ------------
    private void roleChanged() {
        ComboItem roleItem = (ComboItem) comboRole.getSelectedItem();
        if (roleItem == null) return;
        String roleName = roleItem.getName();
        if ("Admin".equalsIgnoreCase(roleName)) {
            comboEmployee.setEnabled(false);
            comboEmployee.setSelectedIndex(-1);
        } else {
            comboEmployee.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        comboRole = new javax.swing.JComboBox<>();
        comboEmployee = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Add User Account");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 21, 174, -1));

        jLabel2.setText("Username:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 75, 88, -1));

        jLabel3.setText("Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 116, 88, -1));

        jLabel4.setText("Role:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 157, 88, -1));

        jLabel5.setText("Employee:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 198, 88, -1));
        getContentPane().add(textUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 72, 177, -1));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 113, 177, -1));

        getContentPane().add(comboRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 154, 177, -1));

        getContentPane().add(comboEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 195, 177, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 276, -1, -1));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 276, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 400, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String username = textUsername.getText().trim();
        String password = new String(txtPassword.getPassword()).trim();
        ComboItem roleItem = (ComboItem) comboRole.getSelectedItem();
        ComboItem employeeItem = (ComboItem) comboEmployee.getSelectedItem();
        String roleName = roleItem.getName();

        if (!"Admin".equalsIgnoreCase(roleName) && employeeItem == null) {
            JOptionPane.showMessageDialog(this, "Employee must be selected for this role.");
            return;
        }
        if (username.isEmpty() || password.isEmpty() || roleItem == null) {
            JOptionPane.showMessageDialog(this, "Please fill all required fields.");
            return;
        }
        try {
            // Check duplicate username
            ResultSet check = DatabaseHelper.executeQuery(
                "SELECT COUNT(*) FROM UserAccount WHERE UserName = ?",
                username
            );
            check.next();
            if (check.getInt(1) > 0) {
                JOptionPane.showMessageDialog(this, "Username already exists.");
                return;
            }
            Integer employeeID = (employeeItem == null) ? null : employeeItem.getId();
            DatabaseHelper.executeUpdate(
                "INSERT INTO UserAccount (UserName, PasswordHash, RoleID, EmployeeID) VALUES (?, ?, ?, ?)",
                username,
                password,                 // plain text for now
                roleItem.getId(),
                employeeID
            );
            JOptionPane.showMessageDialog(this, "User added successfully!");
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error adding user: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddUserDialog dialog = new AddUserDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<ComboItem> comboEmployee;
    private javax.swing.JComboBox<ComboItem> comboRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField textUsername;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
