/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.databaseproject;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hadalkharouf
 */
public class EditSupplierDialog extends javax.swing.JDialog {

    private int supplierID;

    /**
     * Creates new form EditSupplierDialog
     */
    public EditSupplierDialog(java.awt.Frame parent, boolean modal, int supplierID) {
        super(parent, modal);
        initComponents();
        this.supplierID = supplierID;
        loadSupplierData();
        setLocationRelativeTo(parent);

    }

    private void loadSupplierData() {
        String sql = "SELECT * FROM Supplier WHERE SupplierID = ?";
        try (ResultSet rs = DatabaseHelper.executeQuery(sql, supplierID)) {
            if (rs.next()) {
                txtName.setText(rs.getString("SupplierName"));
                txtPhone.setText(rs.getString("Phone"));
                txtEmail.setText(rs.getString("Email"));
                txtAddress.setText(rs.getString("Address"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Supplier");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel4.setText("Phone");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel5.setText("Supplier Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 140, 40));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 140, 40));
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 140, 40));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 140, 40));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 360, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        // Read values FIRST
        String name = txtName.getText().trim();
        String phone = txtPhone.getText().trim();
        String email = txtEmail.getText().trim();
        String address = txtAddress.getText().trim();

        // Validate Supplier Name
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Supplier name is required.");
            txtName.requestFocus();
            return;
        }

        if (!name.matches("[a-zA-Z .'-]{2,100}")) {
            JOptionPane.showMessageDialog(this,
                    "Supplier name must be 2–100 letters only.");
            txtName.requestFocus();
            return;
        }

         // Validate Phone
        if (phone.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Phone number is required.");
            txtPhone.requestFocus();
            return;
        }

        if (!phone.matches("^\\+?[0-9]{7,15}$")) {
            JOptionPane.showMessageDialog(this,
                    "Phone number must contain 7–15 digits.");
            txtPhone.requestFocus();
            return;
        }

        // Validate Email (optional)
        if (!email.isEmpty()) {
            if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
                JOptionPane.showMessageDialog(this, "Invalid email format.");
                txtEmail.requestFocus();
                return;
            }
        }

        // Validate Address length
        if (address.length() > 255) {
            JOptionPane.showMessageDialog(this,
                    "Address must not exceed 255 characters.");
            txtAddress.requestFocus();
            return;
        }

        // UPDATE only AFTER validation passes
        try {
            String sql = "UPDATE Supplier SET SupplierName=?, Phone=?, Email=?, Address=? WHERE SupplierID=?";

            DatabaseHelper.executeUpdate(
                    sql,
                    name,
                    phone,
                    email,
                    address,
                    supplierID
            );

            JOptionPane.showMessageDialog(this, "Supplier updated successfully.");
            dispose();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error updating supplier.");
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
