package com.mycompany.databaseproject;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author hadalkharouf
 */
public class MainMenuFrame extends javax.swing.JFrame {

    private String currentRole;

    public MainMenuFrame(String role) {
        initComponents();
        this.currentRole = role;
        setLocationRelativeTo(null);
        applyRolePermissions();
    }

    private void applyRolePermissions() {
        // Hide everything FIRST (Safer)
        btnManageEmployees.setVisible(false);
        btnManageUserAccounts.setVisible(false);
        btnManageSuppliers.setVisible(false);

        btnManageCars.setVisible(true);
        btnManageCustomers.setVisible(false);
        btnManageContracts.setVisible(false);
        btnManagePayments.setVisible(false);

        // Now role logic
        switch (currentRole) {

            case "Admin":
                btnManageCars.setVisible(true);
                btnManageCustomers.setVisible(true);
                btnManageContracts.setVisible(true);
                btnManagePayments.setVisible(true);

                btnManageEmployees.setVisible(true);
                btnManageUserAccounts.setVisible(true);
                btnManageSuppliers.setVisible(true);
                break;

            case "Manager":
                btnManageCars.setVisible(true);
                btnManageCustomers.setVisible(true);
                btnManageContracts.setVisible(true);
                btnManagePayments.setVisible(true);
                btnManageSuppliers.setVisible(true);
                break;

            case "SalesStaff":
                btnManageCustomers.setVisible(true);
                btnManageContracts.setVisible(true);
                btnManagePayments.setVisible(true);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnManageCars = new javax.swing.JButton();
        btnManageCustomers = new javax.swing.JButton();
        btnManageContracts = new javax.swing.JButton();
        btnManagePayments = new javax.swing.JButton();
        btnManageSuppliers = new javax.swing.JButton();
        btnManageEmployees = new javax.swing.JButton();
        btnManageUserAccounts = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Main Menu");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 163, 40));

        btnManageCars.setText("Manage Cars");
        btnManageCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCarsActionPerformed(evt);
            }
        });
        getContentPane().add(btnManageCars, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 160, 50));

        btnManageCustomers.setText("Manage Customers");
        getContentPane().add(btnManageCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 160, 50));

        btnManageContracts.setText("Manage Contracts");
        getContentPane().add(btnManageContracts, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 160, 50));

        btnManagePayments.setText("Manage Payments");
        getContentPane().add(btnManagePayments, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 160, 50));

        btnManageSuppliers.setText("Manage Suppliers");
        btnManageSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSuppliersActionPerformed(evt);
            }
        });
        getContentPane().add(btnManageSuppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 160, 50));

        btnManageEmployees.setText("Manage Employees");
        getContentPane().add(btnManageEmployees, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 170, 50));

        btnManageUserAccounts.setText("Manage User Accounts");
        getContentPane().add(btnManageUserAccounts, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 170, 50));

        btnLogout.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 0, 153));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 550, -1, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Options");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 150, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/WhatsApp Image 2025-12-04 at 6.19.13 PM.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -60, 640, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCarsActionPerformed
        // TODO add your handling code here:
        new ManageCarsFrame(currentRole).setVisible(true);
    }//GEN-LAST:event_btnManageCarsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();

        LoginFrame login = new LoginFrame();
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnManageSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSuppliersActionPerformed
        // TODO add your handling code here:
        ManageSuppliersFrame frame = new ManageSuppliersFrame(currentRole);
        frame.setVisible(true);
    }//GEN-LAST:event_btnManageSuppliersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainMenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageCars;
    private javax.swing.JButton btnManageContracts;
    private javax.swing.JButton btnManageCustomers;
    private javax.swing.JButton btnManageEmployees;
    private javax.swing.JButton btnManagePayments;
    private javax.swing.JButton btnManageSuppliers;
    private javax.swing.JButton btnManageUserAccounts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
