package com.mycompany.databaseproject;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author hadalkharouf
 */
public class MainMenuFrame extends javax.swing.JFrame {

    private String currentRole;

    public MainMenuFrame(String role) {
        initComponents();
        this.currentRole = role;
        setLocationRelativeTo(null);
        applyRolePermissions();
    }

    private void applyRolePermissions() {
        // Hide EVERYTHING first
        btnManageCars.setVisible(false);
        btnManageCustomers.setVisible(false);
        btnManageContracts.setVisible(false);
        btnManagePayments.setVisible(false);
        btnManageSuppliers.setVisible(false);
        btnManageEmployees.setVisible(false);
        btnManageUserAccounts.setVisible(false);
        jLabel1.setVisible(false); // Admin Options label

        switch (currentRole) {

            case "Admin":
                btnManageCars.setVisible(true);
                btnManageCustomers.setVisible(true);
                btnManageContracts.setVisible(true);
                btnManagePayments.setVisible(true);
                btnManageSuppliers.setVisible(true);
                btnManageEmployees.setVisible(true);
                btnManageUserAccounts.setVisible(true);
                jLabel1.setVisible(true);
                break;

            case "Manager":
                btnManageCars.setVisible(true);
                btnManageCustomers.setVisible(true);
                btnManageContracts.setVisible(true);
                btnManagePayments.setVisible(true);
                btnManageSuppliers.setVisible(true);
                break;

            case "SalesStaff":
                btnManageCustomers.setVisible(true);
                btnManageContracts.setVisible(true);
                btnManagePayments.setVisible(true);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnManageCars = new javax.swing.JButton();
        btnManageCustomers = new javax.swing.JButton();
        btnManageContracts = new javax.swing.JButton();
        btnManagePayments = new javax.swing.JButton();
        btnManageSuppliers = new javax.swing.JButton();
        btnManageEmployees = new javax.swing.JButton();
        btnManageUserAccounts = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnManageFixedAssets = new javax.swing.JButton();
        icon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Main Menu");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 163, 40));

        btnManageCars.setText("Manage Cars");
        btnManageCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCarsActionPerformed(evt);
            }
        });
        getContentPane().add(btnManageCars, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 160, 50));

        btnManageCustomers.setText("Manage Customers");
        btnManageCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustomersActionPerformed(evt);
            }
        });
        getContentPane().add(btnManageCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 160, 50));

        btnManageContracts.setText("Manage Contracts");
        btnManageContracts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageContractsActionPerformed(evt);
            }
        });
        getContentPane().add(btnManageContracts, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 160, 50));

        btnManagePayments.setText("Manage Payments");
        btnManagePayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePaymentsActionPerformed(evt);
            }
        });
        getContentPane().add(btnManagePayments, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 160, 50));

        btnManageSuppliers.setText("Manage Suppliers");
        btnManageSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSuppliersActionPerformed(evt);
            }
        });
        getContentPane().add(btnManageSuppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 160, 50));

        btnManageEmployees.setText("Manage Employees");
        btnManageEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEmployeesActionPerformed(evt);
            }
        });
        getContentPane().add(btnManageEmployees, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 170, 50));

        btnManageUserAccounts.setText("Manage User Accounts");
        btnManageUserAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUserAccountsActionPerformed(evt);
            }
        });
        getContentPane().add(btnManageUserAccounts, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 170, 50));

        btnLogout.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 0, 153));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, -1, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Options");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 150, 40));

        btnManageFixedAssets.setText("Manage Fixed Assets");
        btnManageFixedAssets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFixedAssetsActionPerformed(evt);
            }
        });
        getContentPane().add(btnManageFixedAssets, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 200, 50));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/WhatsApp Image 2025-12-04 at 6.19.13 PM.jpeg"))); // NOI18N
        getContentPane().add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCarsActionPerformed
        // TODO add your handling code here:
        new ManageCarsFrame(currentRole).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManageCarsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnManageSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSuppliersActionPerformed
        // TODO add your handling code here:
        new ManageSuppliersFrame(currentRole).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManageSuppliersActionPerformed

    private void btnManageContractsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageContractsActionPerformed
        // TODO add your handling code here:
        new ManageContractsFrame(currentRole).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManageContractsActionPerformed

    private void btnManageCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustomersActionPerformed
        // TODO add your handling code here:
        new ManageCustomersFrame(currentRole).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManageCustomersActionPerformed

    private void btnManagePaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePaymentsActionPerformed
        // TODO add your handling code here:
        new ManagePaymentsFrame(currentRole).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManagePaymentsActionPerformed

    private void btnManageEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEmployeesActionPerformed
        // TODO add your handling code here:
        new ManageEmployeesFrame(currentRole).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManageEmployeesActionPerformed

    private void btnManageUserAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUserAccountsActionPerformed
        // TODO add your handling code here:
        new ManageUserAccountsFrame(currentRole).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnManageUserAccountsActionPerformed

    private void btnManageFixedAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFixedAssetsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageFixedAssetsActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageCars;
    private javax.swing.JButton btnManageContracts;
    private javax.swing.JButton btnManageCustomers;
    private javax.swing.JButton btnManageEmployees;
    private javax.swing.JButton btnManageFixedAssets;
    private javax.swing.JButton btnManagePayments;
    private javax.swing.JButton btnManageSuppliers;
    private javax.swing.JButton btnManageUserAccounts;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
