package com.mycompany.databaseproject;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ACER
 */
public class ManageUserAccountsFrame extends javax.swing.JFrame {

    private String currentRole;

    public ManageUserAccountsFrame(String role) {
    initComponents();
    this.currentRole = role;
    setLocationRelativeTo(null);

    // Security check
    if (!"Admin".equals(currentRole)) {
        JOptionPane.showMessageDialog(this, "Access denied.");
        new MainMenuFrame(currentRole).setVisible(true);
        this.dispose();
        return;
    }

    initTable();
    loadUsers();
}

    private void initTable() {
    DefaultTableModel model = new DefaultTableModel(
        new String[]{"UserID", "Username", "Role", "Employee", "RoleID"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    tableUsers.setModel(model);
}
    
    private void loadUsers() {
    DefaultTableModel model = (DefaultTableModel) tableUsers.getModel();
    model.setRowCount(0);

    try {
        ResultSet rs = DatabaseHelper.executeQuery(
            "SELECT ua.UserID, ua.UserName, ur.RoleName, " +
            "ISNULL(e.FirstName + ' ' + e.LastName, '---') AS EmployeeName, ua.RoleID " +
            "FROM UserAccount ua " +
            "JOIN UserRole ur ON ua.RoleID = ur.RoleID " +
            "LEFT JOIN Employee e ON ua.EmployeeID = e.EmployeeID"
        );

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("UserID"),
                rs.getString("UserName"),
                rs.getString("RoleName"),
                rs.getString("EmployeeName"),
                rs.getInt("RoleID")
            });
        }

        rs.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading users: " + e.getMessage());
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUsers = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Manage User Accounts");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 21, 229, -1));

        tableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "User ID", "Username", "Role", "Employee Name", "Status"
            }
        ));
        jScrollPane1.setViewportView(tableUsers);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 564, -1));

        jButton1.setText("Add User");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 511, -1, -1));

        jButton2.setText("Reset Password");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 511, -1, -1));

        jButton3.setText("Delete User");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 511, -1, -1));

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 572, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/WhatsApp Image 2025-12-04 at 6.19.13 PM.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int row = tableUsers.getSelectedRow();

    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Please select a user.");
        return;
    }

    int userID = (int) tableUsers.getValueAt(row, 0);

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to delete this user?",
        "Confirm",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) return;

    try {
        DatabaseHelper.executeUpdate(
            "DELETE FROM UserAccount WHERE UserID=?",
            userID
        );

        JOptionPane.showMessageDialog(this, "User deleted successfully!");
        loadUsers();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error deleting user: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int row = tableUsers.getSelectedRow();

    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Please select a user.");
        return;
    }

    int userID = (int) tableUsers.getValueAt(row, 0);

    try {
        DatabaseHelper.executeUpdate(
            "UPDATE UserAccount SET PasswordHash=? WHERE UserID=?",
            "12345", userID
        );

        JOptionPane.showMessageDialog(this, "Password reset to default (12345).");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error resetting password: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new MainMenuFrame(currentRole).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> {
        new ManageUserAccountsFrame("Admin").setVisible(true);
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableUsers;
    // End of variables declaration//GEN-END:variables
}
