package com.mycompany.databaseproject;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author hadalkharouf
 */
public class ManageCarsFrame extends javax.swing.JFrame {

    private String currentRole;

    /**
     * Creates new form ManageCarsFrame
     */
    public ManageCarsFrame() {
        initComponents();
        setLocationRelativeTo(null); // center frame
        loadCarsTable();       // our method to fill the table
    }

    public ManageCarsFrame(String role) {
        this();
        this.currentRole = role;
        applyRolePermissions();
    }

    private void applyRolePermissions() {
        if (currentRole == null) {
            return;
        }

        // Admin full access
        if (currentRole.equalsIgnoreCase("Admin")) {
            btnAddCar.setEnabled(true);
            btnEditCar.setEnabled(true);
            btnDeleteCar.setEnabled(true);
            return;
        }

        // Manager & SalesStaff: view only
        btnAddCar.setEnabled(false);
        btnEditCar.setEnabled(false);
        btnDeleteCar.setEnabled(false);
    }

    private void loadCarsTable() {
        String sql = "SELECT "
                + "c.CarID, "
                + "c.VIN, "
                + "c.PlateNumber, "
                + "cm.ModelName, "
                + "c.Year, "
                + "c.Color, "
                + "cs.StatusName, "
                + "c.Mileage, "
                + "c.PurchaseDate, "
                + "c.PurchasePrice, "
                + "l.LocationName, "
                + "s.SupplierName "
                + "FROM Car c "
                + "JOIN CarModel cm ON c.ModelID = cm.ModelID "
                + "JOIN CarStatus cs ON c.StatusID = cs.StatusID "
                + "JOIN Supplier s ON c.SupplierID = s.SupplierID "
                + "JOIN Location l ON c.LocationID = l.LocationID "
                + "ORDER BY c.CarID";

        DatabaseHelper.fillTable(tblCars, sql);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCars = new javax.swing.JTable();
        btnAddCar = new javax.swing.JButton();
        btnEditCar = new javax.swing.JButton();
        btnDeleteCar = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 3, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 153));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Manage Cars");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        tblCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Car ID", "VIN", "Plate Number", "Model", "Year", "Color", "Status", "Mileage", "Purchase Date", "Purchase Price", "Location", "Supplier"
            }
        ));
        jScrollPane1.setViewportView(tblCars);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 48, 1120, 430));

        btnAddCar.setText("Add Car");
        btnAddCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 500, 120, 50));

        btnEditCar.setText("Edit Car");
        btnEditCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 500, 110, 50));

        btnDeleteCar.setText("Delete Car");
        btnDeleteCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 120, 50));

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, 120, 50));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, 110, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/WhatsApp Image 2025-12-04 at 6.19.13 PM.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 1160, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadCarsTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new MainMenuFrame(currentRole).setVisible(true);
        this.dispose(); //closing this frame 

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCarActionPerformed
        // TODO add your handling code here:
        if (!currentRole.equalsIgnoreCase("Admin")) {
            JOptionPane.showMessageDialog(this, "You are not allowed to add cars.");
            return;
        }
        AddCarDialog dialog = new AddCarDialog(this, true); // modal dialog
        dialog.setVisible(true);

        if (dialog.isSucceeded()) {
            loadCarsTable();   // refresh table after insert
        }
    }//GEN-LAST:event_btnAddCarActionPerformed

    private void btnEditCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCarActionPerformed
        // TODO add your handling code here:
        if (!currentRole.equalsIgnoreCase("Admin")) {
            JOptionPane.showMessageDialog(this, "You are not allowed to edit cars.");
            return;
        }
        int row = tblCars.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a car to edit.");
            return;
        }
        int carID = Integer.parseInt(tblCars.getValueAt(row, 0).toString());

        // Open the dialog with carID
        EditCarDialog dialog = new EditCarDialog(this, true, carID);
        dialog.setVisible(true);

        if (dialog.isSucceeded()) {
            loadCarsTable(); // refresh
        }
    }//GEN-LAST:event_btnEditCarActionPerformed

    private void btnDeleteCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCarActionPerformed
        // TODO add your handling code here:
        if (!currentRole.equalsIgnoreCase("Admin")) {
            JOptionPane.showMessageDialog(this, "You are not allowed to edit cars.");
            return;
        }
        int row = tblCars.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a car to delete.");
            return;
        }

        int carID = Integer.parseInt(tblCars.getValueAt(row, 0).toString());

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete this car?",
                "Delete Car",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            /* =========================
           1. Check car status
            ========================= */
            String statusSql
                    = "SELECT cs.StatusName "
                    + "FROM Car c "
                    + "JOIN CarStatus cs ON c.StatusID = cs.StatusID "
                    + "WHERE c.CarID = ?";

            try ( var rs = DatabaseHelper.executeQuery(statusSql, carID)) {
                if (rs.next()) {
                    String status = rs.getString("StatusName");

                    if (status.equalsIgnoreCase("Sold")) {
                        JOptionPane.showMessageDialog(this,
                                "This car is SOLD and cannot be deleted.");
                        return;
                    }
                }
            }

            /* =========================
           2. Check HireContract
            ========================= */
            String contractSql
                    = "SELECT COUNT(*) FROM HireContract WHERE CarID = ?";

            try ( var rs = DatabaseHelper.executeQuery(contractSql, carID)) {
                if (rs.next() && rs.getInt(1) > 0) {
                    JOptionPane.showMessageDialog(this,
                            "This car is linked to a hire contract and cannot be deleted.");
                    return;
                }
            }

            /* =========================
           3. Soft delete → Retired
        =   ======================== */
            String retireSql
                    = "UPDATE Car SET StatusID = ("
                    + "SELECT StatusID FROM CarStatus WHERE StatusName = 'Retired')"
                    + " WHERE CarID = ?";

            int rows = DatabaseHelper.executeUpdate(retireSql, carID);

            if (rows > 0) {
                JOptionPane.showMessageDialog(this,
                        "Car retired successfully.");
                loadCarsTable();
            }

        } catch (Exception ex) {
            Logger.getLogger(ManageCarsFrame.class.getName())
                    .log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,
                    "Error while deleting car.");
        }
    }//GEN-LAST:event_btnDeleteCarActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCar;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteCar;
    private javax.swing.JButton btnEditCar;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblCars;
    // End of variables declaration//GEN-END:variables
}
