package com.mycompany.databaseproject;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author hadalkharouf
 */
public class ManageSuppliersFrame extends javax.swing.JFrame {

    
    private String currentRole;

    /**
     * Creates new form ManageSuppliersFrame
     */
    public ManageSuppliersFrame(String role) {
        initComponents();
        this.currentRole = role;
        applyRolePermissions();
        loadSuppliersTable();
        setLocationRelativeTo(null);
    }

    private void applyRolePermissions() {
        if (currentRole == null) {
            return;
        }

        // Admin & Manager = full
        if (currentRole.equalsIgnoreCase("Admin") || currentRole.equalsIgnoreCase("Manager")) {
            btnAddSupplier.setEnabled(true);
            btnEditSupplier.setEnabled(true);
            btnDeleteSupplier.setEnabled(true);
            return;
        }

        // SalesStaff = view only
        btnAddSupplier.setEnabled(false);
        btnEditSupplier.setEnabled(false);
        btnDeleteSupplier.setEnabled(false);
    }

    private void loadSuppliersTable() {
        String sql = "SELECT SupplierID, SupplierName, Phone, Email, Address FROM Supplier";
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        try (ResultSet rs = DatabaseHelper.executeQuery(sql)) {
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("SupplierID"),
                    rs.getString("SupplierName"),
                    rs.getString("Phone"),
                    rs.getString("Email"),
                    rs.getString("Address")
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAddSupplier = new javax.swing.JButton();
        btnEditSupplier = new javax.swing.JButton();
        btnDeleteSupplier = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Suppliers");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 120, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Supplier ID", "Supplier Name", "Contact", "Phone", "Email"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 460, 240));

        btnAddSupplier.setText("Add Suppliers");
        btnAddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSupplierActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 130, 30));

        btnEditSupplier.setText("Edit Suppliers");
        btnEditSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSupplierActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 130, 30));

        btnDeleteSupplier.setText("Delete Suppliers");
        btnDeleteSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSupplierActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 130, 30));

        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 130, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/WhatsApp Image 2025-12-04 at 6.19.13 PM.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 670, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new MainMenuFrame(currentRole).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSupplierActionPerformed
        // TODO add your handling code here:
        if (!currentRole.equalsIgnoreCase("Admin")
                && !currentRole.equalsIgnoreCase("Manager")) {

            JOptionPane.showMessageDialog(this, "Access denied");
            return;
        }
        AddSupplierDialog dialog = new AddSupplierDialog(this, true);
        dialog.setVisible(true);
        loadSuppliersTable();

    }//GEN-LAST:event_btnAddSupplierActionPerformed

    private void btnEditSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSupplierActionPerformed
        // TODO add your handling code here:
        if (!currentRole.equalsIgnoreCase("Admin")
                && !currentRole.equalsIgnoreCase("Manager")) {

            JOptionPane.showMessageDialog(this, "Access denied");
            return;
        }

        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select supplier first");
            return;
        }

        int supplierID = Integer.parseInt(
                jTable1.getValueAt(row, 0).toString()
        );

        EditSupplierDialog dialog
                = new EditSupplierDialog(this, true, supplierID);

        dialog.setVisible(true);
        loadSuppliersTable();


    }//GEN-LAST:event_btnEditSupplierActionPerformed

    private void btnDeleteSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSupplierActionPerformed
        try {
            // TODO add your handling code here:
            // صلاحيات الي بيستخدم البرنامج
            if (!currentRole.equalsIgnoreCase("Admin")
                    && !currentRole.equalsIgnoreCase("Manager")) {

                JOptionPane.showMessageDialog(this, "Access denied");
                return;
            }
            // تأكد من اختيار صف
            int row = jTable1.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Select supplier first");
                return;
            }

            //  قراءة SupplierID من العمود الأول
            int supplierID = Integer.parseInt(
                    jTable1.getValueAt(row, 0).toString()
            );

            // تاكيد الحذف
            int confirm = JOptionPane.showConfirmDialog(
                    this,
                    "Are you sure you want to delete this supplier?",
                    "Confirm Delete",
                    JOptionPane.YES_NO_OPTION
            );

            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }
            //تنفيذ  DELETE
            String sql = "DELETE FROM Supplier WHERE SupplierID = ?";
            DatabaseHelper.executeUpdate(sql, supplierID);

            //رسالة + تحديث الجدول
            JOptionPane.showMessageDialog(this, "Supplier deleted successfully");
            loadSuppliersTable();
        } catch (SQLException ex) {
            Logger.getLogger(ManageSuppliersFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnDeleteSupplierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageSuppliersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageSuppliersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageSuppliersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageSuppliersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageSuppliersFrame("Admin").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSupplier;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteSupplier;
    private javax.swing.JButton btnEditSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
